### ISSUE TITLE
유지보수 Todo

### ISSUE THREAD

**Issue by Queue-ri** [Queue-ri/TIL#131]
- [x] dev-note가 docs 바깥에 있어 ci 자동 발행이 안되므로 수정
- [x] ci UTC 설정 (actions는 괜찮은데 로컬에서 실행 시 시간이 안맞음)
- [x] 도메인 업데이트
- [x] Cloudflare Pages 빌드 CI 변경
    - ~Node.js 12 actions are deprecated.~
    - #147 에 따라 MDX 3 때문에 Node.js 22로 올라감
